server:
  port: 8000
  servlet:
    context-path: /BabyHub
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/babyhub?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: root
    password: '!Whgksmf1011'
    
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  
  jackson:
    serialization:
      fail-on-empty-beans: false